import { useMemo, useState } from 'react';
import { Copy, Eye, EyeOff, FileText, Printer, ShieldCheck, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { Modal } from './ui';
import { useGetCenterSettingsQuery } from '../store/api';
import { normalizeCenterSettings } from '../utils/centerSettings';

const copyToClipboard = async (text, successMessage) => {
    await navigator.clipboard.writeText(text);
    toast.success(successMessage);
};

const CredentialHandoffDialog = ({ isOpen, onClose, credentials }) => {
    const [showPassword, setShowPassword] = useState(false);
    const { data: rawCenterSettings } = useGetCenterSettingsQuery(undefined, { skip: !isOpen });
    const centerSettings = normalizeCenterSettings(rawCenterSettings || {});
    const centerName = [centerSettings.center_name, centerSettings.branch_name].filter(Boolean).join(' - ') || centerSettings.center_name;
    const logoUrl = centerSettings.logo_url;
    const centerInitials = String(centerSettings.center_name || 'RCMS').trim().slice(0, 4).toUpperCase();
    const payload = useMemo(() => {
        if (!credentials) return '';
        return [
            `Center: ${centerName}`,
            `${credentials.subjectLabel || 'Name'}: ${credentials.subjectName || '-'}`,
            credentials.identifierLabel && credentials.identifier ? `${credentials.identifierLabel}: ${credentials.identifier}` : null,
            credentials.email ? `Email: ${credentials.email}` : null,
            `Portal: ${credentials.portalLabel || 'Portal'}`,
            `URL: ${credentials.loginUrl || window.location.origin}`,
            `Password: ${credentials.password || '-'}`,
        ].filter(Boolean).join('\n');
    }, [centerName, credentials]);

    if (!credentials) return null;

    const close = () => {
        setShowPassword(false);
        onClose?.();
    };

    const printCredentials = () => {
        const title = `${credentials.portalLabel || 'Portal'} credentials`;
        const win = window.open('', '_blank', 'width=720,height=780');
        if (!win) {
            toast.error('Allow pop-ups to print credentials.');
            return;
        }
        win.document.write(`<!doctype html>
<html>
<head>
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #0f172a; }
    .sheet { border: 1px solid #cbd5e1; border-radius: 12px; padding: 28px; }
    .brand { display: flex; align-items: center; gap: 12px; margin-bottom: 22px; }
    .logo { max-width: 64px; max-height: 44px; object-fit: contain; }
    .mark { display: grid; width: 44px; height: 44px; place-items: center; border-radius: 10px; background: #0e7490; color: white; font-size: 11px; font-weight: 800; }
    .center { margin: 0; color: #0f172a; font-size: 16px; font-weight: 800; }
    h1 { margin: 0 0 8px; font-size: 22px; }
    p { margin: 6px 0; color: #475569; }
    dl { margin-top: 24px; display: grid; gap: 14px; }
    dt { color: #64748b; font-size: 11px; text-transform: uppercase; letter-spacing: .12em; font-weight: 700; }
    dd { margin: 4px 0 0; font-size: 18px; font-weight: 800; }
    .secret { font-family: Consolas, monospace; letter-spacing: .04em; }
    .note { margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; line-height: 1.6; }
  </style>
</head>
<body>
  <section class="sheet">
    <div class="brand">
      ${logoUrl ? `<img class="logo" src="${escapeHtml(logoUrl)}" alt="">` : `<div class="mark">${escapeHtml(centerInitials)}</div>`}
      <p class="center">${escapeHtml(centerName)}</p>
    </div>
    <h1>${escapeHtml(title)}</h1>
    <p>Generated by ${escapeHtml(centerName)}. Ask the recipient to sign in and store this password securely.</p>
    <dl>
      <div><dt>${escapeHtml(credentials.subjectLabel || 'Name')}</dt><dd>${escapeHtml(credentials.subjectName || '-')}</dd></div>
      ${credentials.identifier ? `<div><dt>${escapeHtml(credentials.identifierLabel || 'Identifier')}</dt><dd>${escapeHtml(credentials.identifier)}</dd></div>` : ''}
      ${credentials.email ? `<div><dt>Email</dt><dd>${escapeHtml(credentials.email)}</dd></div>` : ''}
      <div><dt>Login URL</dt><dd>${escapeHtml(credentials.loginUrl || window.location.origin)}</dd></div>
      <div><dt>Password</dt><dd class="secret">${escapeHtml(credentials.password || '-')}</dd></div>
    </dl>
    <p class="note">This page contains a temporary credential. Do not leave it unattended, and do not store printed copies in the patient file unless center policy requires it.</p>
  </section>
</body>
</html>`);
        win.document.close();
        win.focus();
        win.print();
    };

    return (
        <Modal isOpen={isOpen} onClose={close} title={credentials.title || 'Portal credentials'} size="default">
            <div className="space-y-5">
                <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950">
                    <div className="flex items-start gap-3">
                        <ShieldCheck className="mt-0.5 shrink-0 text-amber-600" size={20} />
                        <div>
                            <p className="text-sm font-black">One-time credential handoff</p>
                            <p className="mt-1 text-xs font-semibold leading-5 text-amber-800">
                                This password is shown only after generation. Copy or print it before closing this dialog.
                            </p>
                        </div>
                    </div>
                </div>

                <dl className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4">
                    <CredentialRow label={credentials.subjectLabel || 'Name'} value={credentials.subjectName} />
                    {credentials.identifier ? <CredentialRow label={credentials.identifierLabel || 'Identifier'} value={credentials.identifier} mono /> : null}
                    {credentials.email ? <CredentialRow label="Email" value={credentials.email} mono /> : null}
                    <CredentialRow label="Login URL" value={credentials.loginUrl || window.location.origin} mono />
                    <div>
                        <dt className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Password</dt>
                        <dd className="mt-1 flex items-center gap-2">
                            <code className="min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-3 py-2 font-mono text-sm font-black text-slate-950">
                                {showPassword ? credentials.password : '••••••••••••••••••••••••'}
                            </code>
                            <button
                                type="button"
                                onClick={() => setShowPassword(value => !value)}
                                className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:border-cyan-300 hover:text-cyan-700"
                                title={showPassword ? 'Hide password' : 'Show password'}
                                aria-label={showPassword ? 'Hide password' : 'Show password'}
                            >
                                {showPassword ? <EyeOff size={17} /> : <Eye size={17} />}
                            </button>
                            <button
                                type="button"
                                onClick={() => copyToClipboard(credentials.password, 'Password copied.')}
                                className="flex h-10 w-10 items-center justify-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:border-cyan-300 hover:text-cyan-700"
                                title="Copy password"
                                aria-label="Copy password"
                            >
                                <Copy size={17} />
                            </button>
                        </dd>
                    </div>
                </dl>

                <div className="grid gap-2 sm:grid-cols-3">
                    <button type="button" onClick={() => copyToClipboard(payload, 'Credentials copied.')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-cyan-700 px-4 text-sm font-black text-white transition hover:bg-cyan-800">
                        <Copy size={16} />
                        Copy all
                    </button>
                    <button type="button" onClick={printCredentials} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700 transition hover:border-cyan-300 hover:text-cyan-700">
                        <Printer size={16} />
                        Print
                    </button>
                    <button type="button" onClick={close} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black text-slate-700 transition hover:bg-slate-50">
                        <X size={16} />
                        Done
                    </button>
                </div>

                <div className="flex items-start gap-3 rounded-xl bg-slate-100 p-4 text-xs font-semibold leading-5 text-slate-600">
                    <FileText className="mt-0.5 shrink-0 text-slate-400" size={16} />
                    <p>{credentials.deliveryHint || 'Give this credential directly to the authorized recipient. Ask them not to share it and to keep it in a password manager.'}</p>
                </div>
            </div>
        </Modal>
    );
};

const CredentialRow = ({ label, value, mono = false }) => (
    <div>
        <dt className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">{label}</dt>
        <dd className={`mt-1 truncate text-sm font-black text-slate-950 ${mono ? 'font-mono' : ''}`}>{value || '-'}</dd>
    </div>
);

const escapeHtml = (value) => String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');

export default CredentialHandoffDialog;
