const catalogEvents = [
    'ACCOUNT_LOCKED', 'ACCOUNT_LOCKED_ACCESS', 'AI_ANALYSIS_REQUESTED',
    'AppointmentCancelled', 'AppointmentCreated', 'AppointmentNoShow', 'AppointmentReminder',
    'AppointmentRequested', 'AppointmentRequestReviewed', 'AppointmentRescheduled',
    'BackupCompleted', 'BackupFailed', 'ChatMessageReceived', 'ClaimApproved', 'ClaimPaid',
    'ClaimRejected', 'ClaimSubmitted', 'CONSENT_REVOKED', 'CriticalResultFinalized', 'DATA_EXPORT_REQUESTED',
    'DocumentDownloaded', 'EquipmentDowntimeCreated', 'EquipmentDowntimeResolved', 'EquipmentDowntimeUpdated',
    'EquipmentMaintenanceCreated', 'EquipmentMaintenanceUpdated', 'ExamCreated', 'ExamScheduled', 'ExamStatusChanged',
    'FollowUpReminder', 'IMAGE_VIEW', 'ItemExpired', 'LOGIN_FAILED', 'LowStock',
    'ManualReminder', 'ManualSend', 'MarketingCampaign', 'OrderCreated', 'PartialPaymentException', 'PACS_CONFIG_UPDATED', 'PaymentDue',
    'PaymentReceived', 'PERMISSION_DENIED', 'PrepInstructions', 'PRIVACY_REQUEST_RESOLVED',
    'ProfileUpdateRequested', 'PurchaseOrderReceived', 'RefundProcessed', 'RefundRequested', 'RefundReviewed',
    'ReportReady', 'ResultDelivered', 'STAFF_CREATED', 'STAFF_DEACTIVATED', 'STAFF_UPDATED',
    'STUDY_EXPORTED', 'STUDY_IMPORTED', 'SUPPLY_ADDED_PAYMENT_DUE', 'TOKEN_REUSE_DETECTED',
    'EmergencyAccessGranted', 'EmergencyAccessRevoked', 'PatientAppointmentNoShowNotice', 'CriticalResultEscalated', 'INTEGRATION_FAILED',
    'API_TOKEN_WRITE_SCOPE_DENIED', 'ATTENDANCE_SESSION_AUTO_CAPPED', 'RECEPTION_SHIFT_AUTO_CLOSED',
    'AttendanceAutoAbsent',
    'CASHIER_VARIANCE_REQUIRES_REVIEW', 'LEAVE_REQUEST_SUBMITTED', 'LEAVE_REQUEST_DECIDED',
    'PayrollRunStatusChanged', 'PenaltyImposed', 'PenaltyDisputed', 'PenaltyDisputeResolved', 'PenaltyCancelled',
    'PayrollEmployeesSkipped', 'CredentialExpiring'
];

const activeTemplates = {
    ACCOUNT_LOCKED: ['InApp', 'Email', 'SMS'],
    ACCOUNT_LOCKED_ACCESS: ['InApp', 'Email', 'SMS'],
    AI_ANALYSIS_REQUESTED: ['InApp'],
    AppointmentCancelled: ['Email', 'SMS', 'WhatsApp'],
    AppointmentCreated: ['Email', 'SMS'],
    AppointmentNoShow: ['InApp', 'Email'],
    AppointmentReminder: ['Email', 'SMS', 'WhatsApp'],
    AppointmentRequested: ['InApp'],
    AppointmentRequestReviewed: ['Email'],
    AppointmentRescheduled: ['Email', 'SMS'],
    BackupCompleted: ['InApp'],
    BackupFailed: ['InApp', 'Email', 'SMS'],
    ChatMessageReceived: ['InApp'],
    ClaimApproved: ['InApp', 'Email'],
    ClaimPaid: ['InApp', 'Email'],
    ClaimRejected: ['InApp', 'Email'],
    ClaimSubmitted: ['InApp'],
    CONSENT_REVOKED: ['InApp'],
    CriticalResultFinalized: ['InApp', 'Email', 'SMS', 'WhatsApp'],
    CriticalResultEscalated: ['InApp', 'Email', 'SMS'],
    DATA_EXPORT_REQUESTED: ['InApp', 'Email'],
    DocumentDownloaded: ['InApp'],
    EquipmentDowntimeCreated: ['InApp', 'Email', 'SMS'],
    EquipmentDowntimeResolved: ['InApp'],
    EquipmentDowntimeUpdated: ['InApp', 'Email'],
    EquipmentMaintenanceCreated: ['InApp'],
    EquipmentMaintenanceUpdated: ['InApp'],
    ExamCreated: ['InApp'],
    ExamScheduled: ['InApp'],
    ExamStatusChanged: ['InApp'],
    FollowUpReminder: ['Email', 'SMS'],
    IMAGE_VIEW: ['InApp'],
    ItemExpired: ['InApp', 'Email'],
    LOGIN_FAILED: ['InApp', 'Email'],
    LowStock: ['InApp', 'Email'],
    MarketingCampaign: ['Email', 'SMS', 'WhatsApp'],
    OrderCreated: ['InApp'],
    PartialPaymentException: ['InApp'],
    PACS_CONFIG_UPDATED: ['InApp', 'Email'],
    PaymentDue: ['Email', 'SMS'],
    PaymentReceived: ['Email', 'InApp'],
    PERMISSION_DENIED: ['InApp'],
    PrepInstructions: ['Email', 'SMS'],
    PRIVACY_REQUEST_RESOLVED: ['InApp', 'Email'],
    ProfileUpdateRequested: ['InApp'],
    PurchaseOrderReceived: ['InApp'],
    RefundProcessed: ['InApp', 'Email'],
    RefundRequested: ['InApp'],
    RefundReviewed: ['InApp'],
    ReportReady: ['Email', 'SMS', 'WhatsApp'],
    ResultDelivered: ['Email', 'SMS', 'WhatsApp'],
    STAFF_CREATED: ['InApp'],
    STAFF_DEACTIVATED: ['InApp'],
    STAFF_UPDATED: ['InApp'],
    STUDY_EXPORTED: ['InApp', 'Email'],
    STUDY_IMPORTED: ['InApp'],
    SUPPLY_ADDED_PAYMENT_DUE: ['InApp'],
    TOKEN_REUSE_DETECTED: ['InApp', 'Email', 'SMS'],
    EmergencyAccessGranted: ['InApp', 'Email'],
    EmergencyAccessRevoked: ['InApp'],
    PatientAppointmentNoShowNotice: ['InApp', 'Email'],
    INTEGRATION_FAILED: ['InApp'],
    API_TOKEN_WRITE_SCOPE_DENIED: ['InApp'],
    ATTENDANCE_SESSION_AUTO_CAPPED: ['InApp'],
    RECEPTION_SHIFT_AUTO_CLOSED: ['InApp'],
    AttendanceAutoAbsent: ['InApp'],
    CASHIER_VARIANCE_REQUIRES_REVIEW: ['InApp', 'Email'],
    LEAVE_REQUEST_SUBMITTED: ['InApp'],
    LEAVE_REQUEST_DECIDED: ['InApp'],
    PayrollRunStatusChanged: ['InApp'],
    PenaltyImposed: ['InApp'],
    PenaltyDisputed: ['InApp'],
    PenaltyDisputeResolved: ['InApp'],
    PenaltyCancelled: ['InApp'],
    PayrollEmployeesSkipped: ['InApp'],
    CredentialExpiring: ['InApp', 'Email']
};

const requiredRolePolicies = [
    ['RefundRequested', 'Cashier'], ['RefundRequested', 'Accountant'], ['RefundRequested', 'Admin'],
    ['RefundReviewed', 'Receptionist'], ['RefundReviewed', 'Cashier'], ['RefundReviewed', 'Accountant'], ['RefundReviewed', 'Admin'],
    ['SUPPLY_ADDED_PAYMENT_DUE', 'Cashier'], ['SUPPLY_ADDED_PAYMENT_DUE', 'Accountant'],
    ['PaymentReceived', 'Cashier'], ['PaymentReceived', 'Accountant'], ['PaymentReceived', 'Admin'],
    ['CriticalResultFinalized', 'Radiologist'], ['CriticalResultFinalized', 'Admin'],
    ['CriticalResultEscalated', 'Radiologist'], ['CriticalResultEscalated', 'Admin'],
    ['INTEGRATION_FAILED', 'Admin'], ['INTEGRATION_FAILED', 'Developer'],
    ['ClaimSubmitted', 'Accountant'], ['ClaimSubmitted', 'Admin'],
    ['EquipmentMaintenanceCreated', 'Technician'], ['EquipmentMaintenanceCreated', 'Admin'],
    ['EquipmentMaintenanceUpdated', 'Technician'], ['EquipmentMaintenanceUpdated', 'Admin'],
    ['EquipmentDowntimeCreated', 'Technician'], ['EquipmentDowntimeCreated', 'Receptionist'], ['EquipmentDowntimeCreated', 'Admin'],
    ['EquipmentDowntimeUpdated', 'Technician'], ['EquipmentDowntimeUpdated', 'Receptionist'], ['EquipmentDowntimeUpdated', 'Admin'],
    ['EquipmentDowntimeResolved', 'Technician'], ['EquipmentDowntimeResolved', 'Receptionist'], ['EquipmentDowntimeResolved', 'Admin'],
    ['ExamStatusChanged', 'Admin'], ['ExamStatusChanged', 'Radiologist'], ['ExamStatusChanged', 'Technician'],
    ['ExamStatusChanged', 'Nurse'], ['ExamStatusChanged', 'Receptionist'], ['ExamStatusChanged', 'Accountant'],
    ['PayrollRunStatusChanged', 'Admin'], ['PayrollRunStatusChanged', 'Accountant'], ['PayrollRunStatusChanged', 'HR'],
    ['PenaltyImposed', 'Receptionist'], ['PenaltyImposed', 'Technician'], ['PenaltyImposed', 'HR'],
    ['PenaltyDisputed', 'HR'], ['PenaltyDisputed', 'Admin'],
    ['PenaltyDisputeResolved', 'Receptionist'], ['PenaltyDisputeResolved', 'Technician'],
    ['PenaltyCancelled', 'HR'], ['PenaltyCancelled', 'Admin'],
    ['PayrollEmployeesSkipped', 'HR'], ['PayrollEmployeesSkipped', 'Admin'],
    ['CredentialExpiring', 'HR'], ['CredentialExpiring', 'Admin'],
    ['AppointmentRequested', 'Receptionist'], ['ProfileUpdateRequested', 'Admin'], ['DocumentDownloaded', 'Admin']
];

const renderCases = [
    {
        template: 'Refund {{invoice_number}} for {{amount}} via {{payment_method}}',
        variables: { invoice_number: 'INV-7', amount: '125.00', payment_method: 'Cash' },
        expected: 'Refund INV-7 for 125.00 via Cash'
    },
    {
        template: 'Supply {{item_name}} added; balance {{balance_amount}}',
        variables: { item_name: 'Contrast', balance_amount: '420.00' },
        expected: 'Supply Contrast added; balance 420.00'
    },
    {
        template: 'Results {{order_number}} delivered by {{delivery_method}}',
        variables: { order_number: 'ORD-9', delivery_method: 'WhatsApp Link' },
        expected: 'Results ORD-9 delivered by WhatsApp Link'
    }
];

module.exports = { activeTemplates, catalogEvents, renderCases, requiredRolePolicies };
