// Shared audit vocabulary. Keep event codes stable: dashboards, exports,
// detection rules, and compliance reviews should not depend on free text.

const AUDIT_CATEGORY = Object.freeze({
    AUTH: 'AUTH',
    RBAC: 'RBAC',
    PHI_ACCESS: 'PHI_ACCESS',
    PRIVACY: 'PRIVACY',
    BILLING: 'BILLING',
    CONFIG: 'CONFIG',
    DATA_WRITE: 'DATA_WRITE',
    SECURITY: 'SECURITY',
});

const AUDIT_SEVERITY = Object.freeze({
    DEBUG: 10,
    INFO: 20,
    NOTICE: 30,
    WARNING: 40,
    CRITICAL: 50,
});

const AUDIT_OUTCOME = Object.freeze({
    SUCCESS: 'success',
    FAILURE: 'failure',
    DENIED: 'denied',
});

const AUDIT_ACTOR_TYPE = Object.freeze({
    USER: 'USER',
    SYSTEM: 'SYSTEM',
    PATIENT: 'PATIENT',
    API_TOKEN: 'API_TOKEN',
    INTEGRATION: 'INTEGRATION',
});

const AUDIT_EVENT_FAMILY = Object.freeze({
    AUTH: 'AUTH',
    AUDIT: 'AUDIT',
    USER: 'USER',
    RBAC: 'RBAC',
    PATIENT: 'PATIENT',
    APPOINTMENT: 'APPOINTMENT',
    EXAM: 'EXAM',
    REPORT: 'REPORT',
    BILLING: 'BILLING',
    INSURANCE: 'INSURANCE',
    PACS: 'PACS',
    PORTAL: 'PORTAL',
    PRIVACY: 'PRIVACY',
    INVENTORY: 'INVENTORY',
    HR: 'HR',
    PAYROLL: 'PAYROLL',
    SETTINGS: 'SETTINGS',
    BACKUP: 'BACKUP',
    INTEGRATION: 'INTEGRATION',
    SYSTEM: 'SYSTEM',
    SECURITY: 'SECURITY',
    AI: 'AI',
});

const AUDIT_EVENT_CODES = Object.freeze({
    AUTH_LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
    AUTH_LOGIN_FAILED: 'AUTH.LOGIN_FAILED',
    AUTH_LOGOUT: 'AUTH.LOGOUT',
    AUTH_PASSWORD_CHANGED: 'AUTH.PASSWORD_CHANGED',
    AUTH_TOKEN_REUSED: 'AUTH.TOKEN_REUSED',
    AUDIT_EXPORT_CREATED: 'AUDIT.EXPORT_CREATED',
    AUDIT_CHAIN_VERIFIED: 'AUDIT.CHAIN_VERIFIED',
    AUDIT_DETECTION_RUN: 'AUDIT.DETECTION_RUN',
    AUDIT_ALERT_REVIEWED: 'AUDIT.ALERT_REVIEWED',
    USER_CREATED: 'USER.CREATED',
    USER_UPDATED: 'USER.UPDATED',
    USER_DEACTIVATED: 'USER.DEACTIVATED',
    USER_ROLE_CHANGED: 'USER.ROLE_CHANGED',
    RBAC_PERMISSION_GRANTED: 'RBAC.PERMISSION_GRANTED',
    RBAC_PERMISSION_REVOKED: 'RBAC.PERMISSION_REVOKED',
    RBAC_EMERGENCY_ACCESS_GRANTED: 'RBAC.EMERGENCY_ACCESS_GRANTED',
    PATIENT_VIEWED: 'PATIENT.VIEWED',
    PATIENT_CREATED: 'PATIENT.CREATED',
    PATIENT_UPDATED: 'PATIENT.UPDATED',
    PATIENT_MERGED: 'PATIENT.MERGED',
    PATIENT_EXPORTED: 'PATIENT.EXPORTED',
    PATIENT_ANONYMIZED: 'PATIENT.ANONYMIZED',
    REPORT_DRAFT_CREATED: 'REPORT.DRAFT_CREATED',
    REPORT_FINALIZED: 'REPORT.FINALIZED',
    REPORT_AMENDED: 'REPORT.AMENDED',
    REPORT_PRINTED: 'REPORT.PRINTED',
    REPORT_DOWNLOADED: 'REPORT.DOWNLOADED',
    BILLING_INVOICE_CREATED: 'BILLING.INVOICE_CREATED',
    BILLING_PAYMENT_COLLECTED: 'BILLING.PAYMENT_COLLECTED',
    BILLING_REFUND_REQUESTED: 'BILLING.REFUND_REQUESTED',
    BILLING_REFUND_APPROVED: 'BILLING.REFUND_APPROVED',
    PACS_IMAGE_VIEWED: 'PACS.IMAGE_VIEWED',
    PACS_ACCESS_DENIED: 'PACS.ACCESS_DENIED',
    PACS_INSTANCE_RECEIVED: 'PACS.INSTANCE_RECEIVED',
    PACS_STUDY_IMPORTED: 'PACS.STUDY_IMPORTED',
    PACS_STUDY_RECONCILED: 'PACS.STUDY_RECONCILED',
    PACS_STUDY_QUARANTINED: 'PACS.STUDY_QUARANTINED',
    PACS_STUDY_EXPORTED: 'PACS.STUDY_EXPORTED',
    PACS_WADO_ACCESSED: 'PACS.WADO_ACCESSED',
    PACS_CONFIG_UPDATED: 'PACS.CONFIG_UPDATED',
    PACS_MODALITY_SYNCED: 'PACS.MODALITY_SYNCED',
    PACS_MODALITY_SYNC_FAILED: 'PACS.MODALITY_SYNC_FAILED',
    PACS_MODALITY_ECHO_OK: 'PACS.MODALITY_ECHO_OK',
    PACS_MODALITY_ECHO_FAILED: 'PACS.MODALITY_ECHO_FAILED',
    PACS_MWL_REGENERATED: 'PACS.MWL_REGENERATED',
    PACS_TIERING_TRIGGERED: 'PACS.TIERING_TRIGGERED',
    PACS_AI_ANALYSIS_REQUESTED: 'PACS.AI_ANALYSIS_REQUESTED',
    PACS_AI_ANALYSIS_COMPLETED: 'PACS.AI_ANALYSIS_COMPLETED',
    PACS_AI_ANALYSIS_FAILED: 'PACS.AI_ANALYSIS_FAILED',
    SYSTEM_BACKUP_STARTED: 'SYSTEM.BACKUP_STARTED',
    SYSTEM_BACKUP_COMPLETED: 'SYSTEM.BACKUP_COMPLETED',
    SYSTEM_BACKUP_FAILED: 'SYSTEM.BACKUP_FAILED',
    SYSTEM_JOB_COMPLETED: 'SYSTEM.JOB_COMPLETED',
    SYSTEM_JOB_FAILED: 'SYSTEM.JOB_FAILED',
    SYSTEM_SETTING_CHANGED: 'SYSTEM.SETTING_CHANGED',
    SYSTEM_RETENTION_JOB_RAN: 'SYSTEM.RETENTION_JOB_RAN',
});

const VALID_OUTCOMES = new Set(Object.values(AUDIT_OUTCOME));
const VALID_CATEGORIES = new Set(Object.values(AUDIT_CATEGORY));
const VALID_ACTOR_TYPES = new Set(Object.values(AUDIT_ACTOR_TYPE));
const VALID_EVENT_FAMILIES = new Set(Object.values(AUDIT_EVENT_FAMILY));

const HIGH_RISK_EVENT_CODES = new Set([
    AUDIT_EVENT_CODES.AUTH_TOKEN_REUSED,
    AUDIT_EVENT_CODES.AUDIT_EXPORT_CREATED,
    AUDIT_EVENT_CODES.USER_ROLE_CHANGED,
    AUDIT_EVENT_CODES.RBAC_PERMISSION_GRANTED,
    AUDIT_EVENT_CODES.RBAC_PERMISSION_REVOKED,
    AUDIT_EVENT_CODES.RBAC_EMERGENCY_ACCESS_GRANTED,
    AUDIT_EVENT_CODES.PATIENT_EXPORTED,
    AUDIT_EVENT_CODES.PATIENT_ANONYMIZED,
    AUDIT_EVENT_CODES.REPORT_AMENDED,
    AUDIT_EVENT_CODES.BILLING_REFUND_APPROVED,
    AUDIT_EVENT_CODES.SYSTEM_SETTING_CHANGED,
]);

const outcomeFromStatus = (statusCode) => {
    const code = Number.parseInt(statusCode, 10);
    if (!Number.isFinite(code)) return AUDIT_OUTCOME.SUCCESS;
    if (code === 401 || code === 403) return AUDIT_OUTCOME.DENIED;
    if (code >= 400) return AUDIT_OUTCOME.FAILURE;
    return AUDIT_OUTCOME.SUCCESS;
};

const categoryFromRequest = (method, path = '') => {
    const p = String(path).toLowerCase();
    if (/\/(auth|login|logout|password|token|sessions)/.test(p)) return AUDIT_CATEGORY.AUTH;
    if (/\/(rbac|role|permission)/.test(p)) return AUDIT_CATEGORY.RBAC;
    if (/\/privacy/.test(p)) return AUDIT_CATEGORY.PRIVACY;
    if (/\/(portal\/records|reports|documents|dicom|pacs|examinations)/.test(p)) return AUDIT_CATEGORY.PHI_ACCESS;
    if (/\/(invoices?|payments?|billing|refunds?|claims?)/.test(p)) return AUDIT_CATEGORY.BILLING;
    if (/\/(settings|config)/.test(p)) return AUDIT_CATEGORY.CONFIG;
    if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(String(method).toUpperCase())) return AUDIT_CATEGORY.DATA_WRITE;
    return AUDIT_CATEGORY.SECURITY;
};

const familyFromEventCode = (eventCode) => {
    const family = String(eventCode || '').split('.')[0];
    return VALID_EVENT_FAMILIES.has(family) ? family : AUDIT_EVENT_FAMILY.SYSTEM;
};

const actionFromEventCode = (eventCode, fallback = null) => {
    const parts = String(eventCode || '').split('.');
    return parts.length > 1 ? parts.slice(1).join('.') : fallback;
};

module.exports = {
    AUDIT_CATEGORY,
    AUDIT_SEVERITY,
    AUDIT_OUTCOME,
    AUDIT_ACTOR_TYPE,
    AUDIT_EVENT_FAMILY,
    AUDIT_EVENT_CODES,
    VALID_OUTCOMES,
    VALID_CATEGORIES,
    VALID_ACTOR_TYPES,
    VALID_EVENT_FAMILIES,
    HIGH_RISK_EVENT_CODES,
    outcomeFromStatus,
    categoryFromRequest,
    familyFromEventCode,
    actionFromEventCode,
};
