#!/bin/bash
set -euo pipefail

# Runs after schema.sql on first PostgreSQL container start.
MIGRATIONS=(
  "001_add_roles.sql"
  "002_add_notifications.sql"
  "003_add_inventory.sql"
  "004_expand_appointments.sql"
  "005_add_exam_types.sql"
  "004_performance_indexes.sql"
  "006_dashboard_indexes.sql"
  "007_fix_user_roles_enum.sql"
  "008_fix_appointment_overlap.sql"
  "009_patient_auth_and_search.sql"
  "010_refresh_tokens.sql"
  "011_user_profile_fields.sql"
  "012_patient_engagement_fields.sql"
  "013_extend_patient_demographics.sql"
  "014_scheduling_enhancements.sql"
  "015_referring_doctors.sql"
  "016_order_management.sql"
  "017_patient_queue_management.sql"
  "018_billing_cashier.sql"
  "019_insurance_contracts_claims.sql"
  "020_reporting_typing_workflow.sql"
  "021_result_delivery_management.sql"
  "022_patient_portal_online_access.sql"
  "023_doctor_portal.sql"
  "024_notifications_expanded.sql"
  "025_advanced_inventory.sql"
  "026_equipment_management.sql"
  "027_financial_management.sql"
  "028_hr_management.sql"
  "029_crm_marketing.sql"
  "030_security_events_and_roles.sql"
  "030_encrypt_pii_fields.sql"
  "031_portal_schema_consistency.sql"
  "031_refresh_token_audit.sql"
  "032_notification_preferences_consistency.sql"
  "032_performance_indexes.sql"
  "024_reporting_indices.sql"
  "033_expand_rbac_permissions.sql"
  "034_invoice_payment_discounts.sql"
  "035_patient_anonymized_status.sql"
  "036_refund_review_workflow.sql"
  "037_refund_cashier_shift.sql"
  "038_tamper_evident_audit.sql"
  "039_patient_merge_lineage.sql"
  "040_financial_integrity.sql"
  "041_claim_status_history.sql"
  "042_encrypt_notification_content.sql"
  "043_user_preferences.sql"
  "052_pacs_imaging.sql"
  "053_modality_dicom_config.sql"
  "055_pacs_permissions.sql"
  "056_pacs_quarantine_legacy_schema.sql"
  "064_pacs_ai_analysis_jobs.sql"
  "077_audit_classification.sql"
  "085_add_audit_change_columns.sql"
  "086_structured_audit_events.sql"
  "087_audit_governance_permissions.sql"
  "057_case_report_permissions.sql"
  "114_financial_branch_integrity.sql"
  "115_reception_integrity.sql"
)

for file in "${MIGRATIONS[@]}"; do
  echo "Applying migration: $file"
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "/migrations/$file"
done

echo "Applying seeds..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "/seeds/seed-rbac.sql"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "/seeds/seed.sql"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "/seeds/seed-demo-modules.sql"

echo "Database initialization complete."
