-- Ensure patient and referring-doctor inboxes receive actionable in-app copies
-- of the external events already generated by clinical and billing workflows.
INSERT INTO notification_templates (event_type, channel, language, subject, body, is_active) VALUES
('AppointmentCreated', 'InApp', 'en', 'Appointment Created', 'Your appointment for order {{order_number}} has been created for {{appointment_time}}.', TRUE),
('AppointmentReminder', 'InApp', 'en', 'Appointment Reminder', 'Reminder: your appointment for order {{order_number}} is scheduled for {{appointment_time}}.', TRUE),
('AppointmentCancelled', 'InApp', 'en', 'Appointment Cancelled', 'Appointment {{order_number}} was cancelled. Reason: {{cancellation_reason}}.', TRUE),
('AppointmentRescheduled', 'InApp', 'en', 'Appointment Rescheduled', 'Appointment {{order_number}} was moved to {{appointment_time}}. Reason: {{reschedule_reason}}.', TRUE),
('PrepInstructions', 'InApp', 'en', 'Preparation Instructions', '{{prep_instructions}}', TRUE),
('PaymentDue', 'InApp', 'en', 'Payment Due', 'Payment is due for invoice {{invoice_number}}. Amount: {{amount}}.', TRUE),
('ReportReady', 'InApp', 'en', 'Report Ready', 'The report for order {{order_number}} is ready in the secure portal.', TRUE),
('ResultDelivered', 'InApp', 'en', 'Result Delivered', 'Results for order {{order_number}} were delivered via {{delivery_method}}.', TRUE),
('AppointmentRequestReviewed', 'InApp', 'en', 'Appointment Request Updated', 'Your appointment request status is {{status}}. Notes: {{staff_notes}}', TRUE),
('RefundProcessed', 'InApp', 'en', 'Refund Processed', 'Refund for invoice {{invoice_number}} was processed. Amount: {{amount}}. Reason: {{reason}}.', TRUE),
('CriticalResultFinalized', 'InApp', 'en', 'Critical Result Requires Acknowledgement', 'A critical diagnostic result for order {{order_number}} requires immediate review and acknowledgement.', TRUE)
ON CONFLICT (event_type, channel, language) DO UPDATE SET
    subject = EXCLUDED.subject,
    body = EXCLUDED.body,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

UPDATE notification_event_catalog
SET default_channels = ARRAY(
    SELECT DISTINCT channel
    FROM unnest(default_channels || ARRAY['InApp']::text[]) AS channel
)
WHERE event_type IN (
    'AppointmentCreated', 'AppointmentReminder', 'AppointmentCancelled',
    'AppointmentRescheduled', 'PrepInstructions', 'PaymentDue', 'ReportReady',
    'ResultDelivered', 'AppointmentRequestReviewed', 'RefundProcessed',
    'CriticalResultFinalized'
);
