ALTER TABLE report_versions
    ADD COLUMN IF NOT EXISTS signature_hash VARCHAR(128),
    ADD COLUMN IF NOT EXISTS signatory_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS signatory_role VARCHAR(100),
    ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP WITH TIME ZONE;
