/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: 'var(--rcms-canvas)',
                foreground: 'var(--rcms-ink)',
                surface: 'var(--rcms-surface)',
                border: 'var(--rcms-line)',
                input: 'var(--rcms-line-strong)',
                'muted-foreground': 'var(--rcms-muted)',
                accent: {
                    DEFAULT: 'var(--rcms-accent)',
                    dark: 'var(--rcms-accent-dark)',
                    light: '#63B3ED',
                    foreground: '#ffffff',
                },
                primary: {
                    50: '#edf6ff',
                    100: '#d9ecff',
                    200: '#b9dcfb',
                    300: '#8bc9f1',
                    400: '#4da9e8',
                    500: '#1685d1',
                    600: '#075cb7',
                    700: '#064f9f',
                    800: '#0b3b78',
                    900: '#082761',
                },
                coral: {
                    50: '#fff5f3',
                    100: '#ffe0db',
                    200: '#ffc4b8',
                    300: '#ff9e8a',
                    400: '#FF6B57',
                    500: '#e85a47',
                    600: '#c44a3a',
                    700: '#9e3a2e',
                    800: '#7a2d24',
                    900: '#5c211d',
                },
                navy: {
                    50: '#f0f4f8',
                    100: '#d9e2ec',
                    200: '#bcccdc',
                    300: '#9fb3c8',
                    400: '#829ab1',
                    500: '#627d98',
                    600: '#4a6580',
                    700: '#3a4f66',
                    800: '#2a3b4d',
                    900: '#0A2540',
                    950: '#071B32',
                },
                medical: {
                    blue: '#3b82f6',
                    green: '#10b981',
                    purple: '#8b5cf6',
                    amber: '#f59e0b',
                    cyan: '#06b6d4',
                    indigo: '#6366f1',
                },
            },
            fontFamily: {
                sans: ['Manrope', 'Noto Sans Arabic', 'system-ui', 'sans-serif'],
                arabic: ['Noto Sans Arabic', 'Manrope', 'system-ui', 'sans-serif'],
                display: ['Manrope', 'Noto Sans Arabic', 'system-ui', 'sans-serif'],
                pixel: ['"Space Mono"', 'monospace'],
                mono: ['"JetBrains Mono"', 'monospace'],
            },
            boxShadow: {
                'card': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
                'card-hover': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.05)',
                'elevated': '0 20px 60px -30px rgba(10, 37, 64, 0.25)',
                'glow': '0 0 40px rgba(7, 92, 183, 0.16)',
                'glow-coral': '0 0 40px rgba(255, 107, 87, 0.15)',
                'glow-teal': '0 0 40px rgba(77, 169, 232, 0.16)',
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-in',
                'slide-up': 'slideUp 0.4s ease-out',
                'fade-in-up': 'fadeInUp 0.7s ease-out both',
                'fade-in-down': 'fadeInDown 0.7s ease-out both',
                'fade-in-left': 'fadeInLeft 0.7s ease-out both',
                'fade-in-right': 'fadeInRight 0.7s ease-out both',
                'scale-in': 'scaleIn 0.5s ease-out both',
                'float': 'float 6s ease-in-out infinite',
                'float-slow': 'float 9s ease-in-out infinite',
                'blob': 'blob 12s ease-in-out infinite',
                'gradient-x': 'gradientX 6s ease infinite',
                'shimmer': 'shimmer 2.5s linear infinite',
                'marquee': 'marquee 30s linear infinite',
                'pulse-ring': 'pulseRing 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'spin-slow': 'spin 18s linear infinite',
                'scan-line': 'scanLine 3.5s ease-in-out infinite',
                'pulse-slow': 'pulseSlow 4s ease-in-out infinite alternate',
                'drift': 'drift 22s ease-in-out infinite',
                'glow-pulse': 'glowPulse 3s ease-in-out infinite alternate',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(10px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                fadeInUp: {
                    '0%': { opacity: '0', transform: 'translateY(40px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                fadeInDown: {
                    '0%': { opacity: '0', transform: 'translateY(-40px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                fadeInLeft: {
                    '0%': { opacity: '0', transform: 'translateX(-40px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                fadeInRight: {
                    '0%': { opacity: '0', transform: 'translateX(40px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.9)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-18px)' },
                },
                blob: {
                    '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
                    '33%': { transform: 'translate(30px, -40px) scale(1.1)' },
                    '66%': { transform: 'translate(-20px, 20px) scale(0.95)' },
                },
                gradientX: {
                    '0%, 100%': { backgroundPosition: '0% 50%' },
                    '50%': { backgroundPosition: '100% 50%' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                marquee: {
                    '0%': { transform: 'translateX(0)' },
                    '100%': { transform: 'translateX(-50%)' },
                },
                pulseRing: {
                    '0%': { transform: 'scale(0.8)', opacity: '0.8' },
                    '80%, 100%': { transform: 'scale(2.2)', opacity: '0' },
                },
                scanLine: {
                    '0%': { transform: 'translateY(-100%)', opacity: '0' },
                    '10%, 90%': { opacity: '1' },
                    '100%': { transform: 'translateY(100%)', opacity: '0' },
                },
                pulseSlow: {
                    '0%': { transform: 'scale(1)', opacity: '0.6' },
                    '100%': { transform: 'scale(1.1)', opacity: '1' },
                },
                drift: {
                    '0%': { transform: 'translate3d(0, 0, 0) scale(1)' },
                    '50%': { transform: 'translate3d(3%, -4%, 0) scale(1.12)' },
                    '100%': { transform: 'translate3d(0, 0, 0) scale(1)' },
                },
                glowPulse: {
                    '0%': { boxShadow: '0 0 20px rgba(7,92,183,0.1)' },
                    '100%': { boxShadow: '0 0 40px rgba(7,92,183,0.25)' },
                },
            },
        },
    },
    plugins: [],
}
